### ISSUE TITLE
Game crashes when visiting the blue house

### ISSUE THREAD

**Issue by atyo416** [Grimmys/rpg_tactical_fantasy_game#8]
The game crashes when visiting the blue house at the top of the map.  Error message is included below

Traceback (most recent call last):
  File "main.py", line 49, in <module>
    quit_game = start_screen.click(e.button, e.pos)
  File "C:\Users\Aaron\Downloads\rpg_tactical_fantasy_game-master\rpg_tactical_fantasy_game-master\src\StartScreen.py", line 282, in click
    self.level.click(button, pos)
  File "C:\Users\Aaron\Downloads\rpg_tactical_fantasy_game-master\rpg_tactical_fantasy_game-master\src\Level.py", line 1190, in click
    self.left_click(pos)
  File "C:\Users\Aaron\Downloads\rpg_tactical_fantasy_game-master\rpg_tactical_fantasy_game-master\src\Level.py", line 1123, in left_click
    self.interact(self.selected_player, ent, interact)
  File "C:\Users\Aaron\Downloads\rpg_tactical_fantasy_game-master\rpg_tactical_fantasy_game-master\src\Level.py", line 509, in interact
    entries = target.interact(actor)
  File "C:\Users\Aaron\Downloads\rpg_tactical_fantasy_game-master\rpg_tactical_fantasy_game-master\src\Building.py", line 20, in interact
    for talk in self.interaction['talks']:
KeyError: 'talks'

**Comment by Grimmys** [comment]
Hello,

The latest commit should fix it.

Thank you !
